export const fakeData = {
  totalWeight: 0,
  totalVehicle: 0,
  gmtPerVehicle: 0,
  colData: [
    {name: 'Hầm 1', bridge: 'Cầu nâng cảng', totalWeight: 0, totalVehicle: 0},
    {name: 'Hầm 2', bridge: 'Cầu nâng cảng', totalWeight: 0, totalVehicle: 0},
    {name: 'Hầm 3', bridge: 'Cầu nâng cảng', totalWeight: 0, totalVehicle: 0},
    {name: 'Hầm 4', bridge: 'Cầu nâng VJC', totalWeight: 0, totalVehicle: 0},
    {name: 'Hầm 5', bridge: 'Cầu nâng VJC', totalWeight: 0, totalVehicle: 0},
    {name: 'Hầm 6', bridge: 'Cầu nâng VJC', totalWeight: 0, totalVehicle: 0},
  ],
  rowData: [
    {
      date: '9/30/2023',
      shift: [
        {
          time: '0-6',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
        {
          time: '6-12',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
        {
          time: '12-18',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
        {
          time: '18-24',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
      ],
    },
    {
      date: '10/01/2023',
      shift: [
        {
          time: '0-6',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
        {
          time: '6-12',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
        {
          time: '12-18',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
        {
          time: '18-24',
          totalWeight: 0,
          totalVehicle: 0,
          gmtPerVehicle: 0,
          tunel: [
            {name: 'Hầm 1', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 2', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 3', bridge: 'Cầu nâng cảng', weight: 0, vehicle: 0},
            {name: 'Hầm 4', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 5', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
            {name: 'Hầm 6', bridge: 'Cầu nâng VJC', weight: 0, vehicle: 0},
          ],
        },
      ],
    },
  ],
};
